server:
  port: 7000
  servlet:
    context-path: /user
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-client-user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    tomcat:
      max-active: 4
      max-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8000/eureka/
#eureka依赖feign, feign依赖hystrix
feign:
  hystrix:
    enabled: true
